# ======================================================== #
# bartender additions
- type: loadoutGroup
  id: FloofBartenderGloves
  name: loadout-group-service-bartender-gloves
  parent: [ PassengerGloves ]
  minLimit: 0
  maxLimit: 1
  loadouts:
  - ClothingHandsBartenderWarmers

- type: loadoutGroup
  id: FloofBartenderShoes
  name: loadout-group-service-bartender-shoes
  parent: [PassengerShoes]
  minLimit: 1
  maxLimit: 1
  loadouts:
  - ClothingShoesColorBlack

- type: loadoutGroup
  id: FloofUndergarmentTopBartender
  parent: FloofUndergarmentTopPassenger
  loadouts: [] # Nuthing here yet

- type: loadoutGroup
  id: FloofUndergarmentBottomBartender
  parent: FloofUndergarmentBottomPassenger
  loadouts:
  - UniformBartenderThong

- type: loadoutGroup
  id: FloofSocksBartender
  parent: FloofSocksPassenger
  loadouts:
  - ClothingUnderSocksBartender

- type: loadoutGroup
  id: FloofBartenderPda
  abstract: true
  loadouts:
  - ClothingNeckCollarEmotionalSupportBartender

- type: loadoutGroup
  id: FloofBartenderGlasses
  abstract: true
  parent: [FloofGlasses]
  name: loadout-group-bartender-glasses
  minLimit: 0
  loadouts:
  - LoadoutBartenderBeerGoggles # Euphoria


# ======================================================== #
# musician additions
- type: loadoutGroup
  id: FloofMusicianGloves
  name: loadout-group-service-musician-gloves
  parent: [ PassengerGloves ]
  minLimit: 0
  maxLimit: 1
  loadouts:
  - ClothingHandsMusicianWarmers

- type: loadoutGroup
  id: FloofMusicianShoes
  name: loadout-group-service-musician-shoes
  parent: [PassengerShoes]
  minLimit: 1
  maxLimit: 1
  loadouts:
  - LaceupShoes

- type: loadoutGroup
  id: FloofServiceMusicianPDAs
  name: loadout-group-musician-pda
  minLimit: 1
  maxLimit: 1
  loadouts:
  - MusicianPDA
  - ClothingNeckCollarEmotionalSupportMusician

- type: loadoutGroup
  id: FloofUndergarmentTopMusician
  parent: FloofUndergarmentTopPassenger
  loadouts: [] # Nuthing here yet

- type: loadoutGroup
  id: FloofUndergarmentBottomMusician
  parent: FloofUndergarmentBottomPassenger
  loadouts:
  - UniformMusicianThong

- type: loadoutGroup
  id: FloofSocksMusician
  parent: FloofSocksPassenger
  loadouts:
  - ClothingUnderSocksMusician

- type: loadoutGroup
  id: MusicianGlasses
  parent: [FloofGlasses] # Floofstation
  name: loadout-group-musician-glasses
  minLimit: 1
  loadouts:
  - LoadoutMusicianGlassesSunglasses
  - Glasses
  - GlassesCheapSunglasses
  - GlassesJamjar
  - GlassesJensen


# ======================================================== #
# janitor additions
- type: loadoutGroup
  id: FloofJanitorGloves
  parent: [PassengerGloves]
  abstract: true
  minLimit: 0
  maxLimit: 1
  loadouts:
  - ClothingHandsJanitorWarmers

- type: loadoutGroup
  id: FloofJanitorShoes
  name: loadout-group-service-janitor-shoes
  parent: [PassengerShoes]
  minLimit: 1
  maxLimit: 1
  loadouts:
  - ClothingShoesGaloshes

- type: loadoutGroup
  id: FloofJanitorPda
  abstract: true
  loadouts:
  - ClothingNeckCollarEmotionalSupportJanitor

- type: loadoutGroup
  id: FloofUndergarmentTopJanitor
  parent: FloofUndergarmentTopPassenger
  loadouts: [] # Nuthing here yet

- type: loadoutGroup
  id: FloofUndergarmentBottomJanitor
  parent: FloofUndergarmentBottomPassenger
  loadouts:
  - UniformJanitorThong

- type: loadoutGroup
  id: FloofSocksJanitor
  parent: FloofSocksPassenger
  loadouts:
  - ClothingUnderSocksJanitor

# ======================================================== #
# chef additions
- type: loadoutGroup
  id: FloofChefGloves
  name: loadout-group-service-chef-gloves
  parent: [PassengerGloves]
  minLimit: 0
  maxLimit: 1
  loadouts:
  - ClothingHandsChefWarmers

- type: loadoutGroup
  id: FloofChefShoes
  name: loadout-group-service-chef-shoes
  parent: [PassengerShoes]
  minLimit: 1
  maxLimit: 1
  loadouts:
  - ClothingShoesColorBlack
  - ClothingShoesChef
  - ClothingShoesBootsWinterChef

- type: loadoutGroup
  id: FloofUndergarmentTopChef
  parent: FloofUndergarmentTopPassenger
  loadouts: [] # Nuthing here yet

- type: loadoutGroup
  id: FloofUndergarmentBottomChef
  parent: FloofUndergarmentBottomPassenger
  loadouts:
  - UniformChefThong

- type: loadoutGroup
  id: FloofSocksChef
  parent: FloofSocksPassenger
  loadouts:
  - ClothingUnderSocksChef

- type: loadoutGroup
  id: FloofChefPdas
  abstract: true
  loadouts:
  - ClothingNeckCollarEmotionalSupportChef

# ======================================================== #
- type: loadoutGroup
  id: FloofBotanistGloves
  name: loadout-group-service-botanist-gloves
  parent: [PassengerGloves]
  minLimit: 0
  maxLimit: 1
  loadouts:
  - ClothingHandsGlovesLeather
  - ClothingHandsServiceWarmers

- type: loadoutGroup
  id: FloofBotanistShoes
  name: loadout-group-service-botanist-shoes
  parent: [PassengerShoes]
  minLimit: 1
  maxLimit: 1
  loadouts:
  - ClothingShoesColorBlack
  - ClothingUnderSocksService

- type: loadoutGroup
  id: FloofServiceBotanistPDAs
  name: loadout-group-botanist-pda
  minLimit: 1
  maxLimit: 1
  loadouts:
  - BotanistPDA
  - ClothingNeckCollarEmotionalSupportBotanist

- type: loadoutGroup
  id: FloofUndergarmentTopBotanist
  parent: FloofUndergarmentTopPassenger
  loadouts: [] # Nuthing here yet

- type: loadoutGroup
  id: FloofUndergarmentBottomBotanist
  parent: FloofUndergarmentBottomPassenger
  loadouts:
  - UniformServiceThong

- type: loadoutGroup
  id: FloofSocksBotanist
  parent: FloofSocksPassenger
  loadouts:
  - ClothingUnderSocksService



# ======================================================== #
# mime additions
- type: loadoutGroup
  id: EuphoriaMimeShoes
  name: loadout-group-service-mime-shoes
  parent: [PassengerShoes]
  minLimit: 1
  maxLimit: 1
  loadouts:
  - WhiteShoes
  - ClothingShoesBootsWinterMime


# ======================================================== #
# gladiator additions
- type: loadoutGroup
  id: FloofGladiatorPDAs
  name: loadout-group-gladiator-pdas
  minLimit: 1
  maxLimit: 1
  loadouts:
  - GladiatorPDA


# ======================================================== #
# martial artist pda
- type: loadoutGroup
  id: FloofMartialArtistPDAs
  name: loadout-group-martial-artist-pdas
  minLimit: 1
  maxLimit: 1
  loadouts:
  - MartialArtistPDA


# ======================================================== #
# boxer pda
- type: loadoutGroup
  id: FloofBoxerPDAs
  name: loadout-group-boxer-pdas
  minLimit: 1
  maxLimit: 1
  loadouts:
  - BoxerPDA
  - ClothingNeckCollarEmotionalSupportBoxer


# ======================================================== #
# Service worker additions
- type: loadoutGroup
  id: ServiceWorkerNeck
  parent: [CommonCollars, Scarfs]
  minLimit: 0
  loadouts: []

- type: loadoutGroup
  id: ServiceWorkerGloves
  parent: [PassengerGloves]
  minLimit: 0
  loadouts:
  - ClothingHandsServiceWarmers

- type: loadoutGroup
  id: FloofServiceWorkerPDAs
  name: loadout-group-service-worker-pdas
  loadouts:
  - ServiceWorkerPDA
  - ClothingNeckCollarEmotionalSupportServiceWorker

- type: loadoutGroup
  id: FloofUndergarmentTopSerivceWorker
  parent: FloofUndergarmentTopPassenger
  loadouts: [] # Nuthing here yet

- type: loadoutGroup
  id: FloofUndergarmentBottomSerivceWorker
  parent: FloofUndergarmentBottomPassenger
  loadouts:
  - UniformServiceThong

- type: loadoutGroup
  id: FloofSocksSerivceWorker
  parent: FloofSocksPassenger
  loadouts:
  - ClothingUnderSocksService


# ======================================================== #
- type: loadoutGroup
  id: FloofClownPda
  abstract: true
  loadouts:
  - ClothingNeckCollarEmotionalSupportClown


# ======================================================== #
- type: loadoutGroup
  id: FloofServiceMimePDAs
  name: loadout-group-mime-pda
  minLimit: 1
  maxLimit: 1
  loadouts:
  - MimePDA
  - ClothingNeckCollarEmotionalSupportMime


# ======================================================== #
- type: loadoutGroup
  id: FloofServiceReporterPDAs
  name: loadout-group-reporters-pda
  minLimit: 1
  maxLimit: 1
  loadouts:
  - ReporterPDA
  - ClothingNeckCollarEmotionalSupportReporter


# ======================================================== #
- type: loadoutGroup
  id: FloofServicePrisonerPDAs
  name: loadout-group-prisoner-pda
  minLimit: 1
  maxLimit: 1
  loadouts:
  - PrisonerPDA
  - ClothingNeckCollarEmotionalSupportPrisoner
